version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8080:8000" # Laravel exposto na porta 8080 do host
    depends_on:
      - mysql
      - wppconnect
    environment:
      - WHATSAPP_API_URL=http://wppconnect:21465
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql

  wppconnect:
    build:
      context: ./wppconnect-server
      dockerfile: Dockerfile
    container_name: wppconnect
    ports:
      - "21465:21465"
    volumes:
      - wppconnect_tokens:/usr/src/wpp-server/wppconnect_tokens
    environment:
      - NODE_ENV=production

volumes:
  mysql_data:
  wppconnect_tokens:
